# Generated by Django 6.1 on 2026-09-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartline',
            name='final_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
