# Generated by Django 6.1 on 2026-09-05 15:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0002_cart_line_final_unit_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuTemplate',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('family', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('spec', models.JSONField(default=dict)),
                ('sort', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort', 'code'],
            },
        ),
        migrations.AddField(
            model_name='cartline',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.CreateModel(
            name='DinerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('accepts_data', models.BooleanField(default=False)),
                ('marketing', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('discount_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email'], name='experience__email_940089_idx')],
            },
        ),
        migrations.AddField(
            model_name='diner',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diners', to='experience_app.dineraccount'),
        ),
        migrations.CreateModel(
            name='VenueMenuSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_slug', models.SlugField(max_length=60)),
                ('venue_slug', models.SlugField(max_length=60)),
                ('palette', models.JSONField(default=dict)),
                ('typography', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='experience_app.menutemplate')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('restaurant_slug', 'venue_slug'), name='uniq_venue_menu_settings')],
            },
        ),
    ]
