# Generated by Django 6.1 on 2026-09-05 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0003_menu_templates_account_and_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='dineraccount',
            name='discount_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discount_accounts', to='experience_app.order'),
        ),
        migrations.AddField(
            model_name='dineraccount',
            name='registration_key',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
