# Generated by Django 6.1 on 2026-09-05 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0004_dineraccount_discount_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesession',
            name='confirming',
            field=models.BooleanField(default=False),
        ),
    ]
