# Generated by Django 6.1 on 2026-09-05 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0005_tablesession_confirming'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignupDiscountClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experience_app.order')),
            ],
        ),
    ]
