# Generated by Django 6.1 on 2026-09-12 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0007_diner_benefit_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinerFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_slug', models.SlugField(max_length=60)),
                ('venue_slug', models.SlugField(max_length=60)),
                ('product_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='experience_app.dineraccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'restaurant_slug', 'venue_slug', 'product_id'), name='unique_diner_favorite')],
            },
        ),
    ]
