# Generated by Django 6.1 on 2026-09-12 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0008_diner_favorites'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('dish_ratings', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience_app.diner')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='experience_app.order')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('order', 'diner'), name='unique_diner_order_feedback'), models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='feedback_rating_1_to_5')],
            },
        ),
    ]
