# Generated by Django 6.1 on 2026-09-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0009_dinerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='dineraccount',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
