# Generated by Django 6.1 on 2026-09-12 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0010_dineraccount_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartline',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_lines', to='experience_app.dineraccount'),
        ),
    ]
