# Generated by Django 6.1 on 2026-09-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0012_dinerpasswordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartline',
            name='takeaway',
            field=models.BooleanField(default=False),
        ),
    ]
