# Generated by Django 6.1 on 2026-09-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0013_cartline_takeaway'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartline',
            name='benefits_reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartline',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='cartline',
            name='loyalty_card_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diner',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
