# Generated by Django 6.1 on 2026-09-14 00:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0014_menu_benefits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant_slug', models.SlugField(max_length=60)),
                ('venue_slug', models.SlugField(max_length=60)),
                ('idempotency_key', models.UUIDField()),
                ('customer', models.JSONField()),
                ('lines', models.JSONField()),
                ('quote', models.JSONField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('restaurant_slug', 'venue_slug', 'idempotency_key'), name='channel_order_unique_request')],
            },
        ),
    ]
