# Generated by Django 6.1 on 2026-09-14 01:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0015_channelorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('restaurant', models.SlugField(max_length=60)),
                ('venue', models.SlugField(max_length=60)),
                ('channel', models.CharField(max_length=16)),
                ('participant', models.CharField(max_length=100)),
                ('history', models.JSONField(default=list)),
                ('lease_until', models.DateTimeField(null=True)),
                ('lease_token', models.UUIDField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'venue', 'channel', 'participant'), name='agent_conversation_identity')],
            },
        ),
        migrations.CreateModel(
            name='AgentDailyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.SlugField(max_length=60)),
                ('day', models.DateField()),
                ('attempts', models.PositiveIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('restaurant', 'day'), name='agent_daily_restaurant')],
            },
        ),
    ]
