# Generated by Django 6.1 on 2026-09-14 01:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0016_agentconversation_agentdailyusage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCartSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField()),
                ('product_id', models.PositiveIntegerField()),
                ('qty', models.PositiveIntegerField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experience_app.diner')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='experience_app.cartline')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('diner', 'message_id', 'product_id'), name='agent_card_selection')],
            },
        ),
    ]
