# Generated by Django 6.1 on 2026-09-14 03:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0017_agentcartselection'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_slug', models.SlugField(max_length=60)),
                ('venue_slug', models.SlugField(max_length=60)),
                ('provider', models.SlugField(default='wompi')),
                ('environment', models.CharField(default='test', max_length=10)),
                ('enabled', models.BooleanField(default=False)),
                ('public_key', models.CharField(blank=True, max_length=200)),
                ('secrets_cipher', models.TextField(blank=True)),
                ('payment_method_id', models.PositiveIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('restaurant_slug', 'venue_slug', 'provider', 'environment'), name='unique_venue_gateway_environment')],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_in_cents', models.PositiveBigIntegerField()),
                ('method', models.CharField(max_length=40)),
                ('status', models.CharField(default='CREATING', max_length=20)),
                ('provider_id', models.CharField(blank=True, max_length=100)),
                ('credentials_cipher', models.TextField()),
                ('payment_method_id', models.PositiveIntegerField(null=True)),
                ('reconciled', models.BooleanField(default=False)),
                ('needs_review', models.BooleanField(default=False)),
                ('qr_image', models.TextField(blank=True)),
                ('redirect_url', models.URLField(blank=True, max_length=2048)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checked_at', models.DateTimeField(null=True)),
                ('diner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experience_app.diner')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experience_app.order')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='experience_app.tablesession')),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='experience_app.paymentgateway')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['CREATING', 'UNKNOWN', 'PENDING', 'APPROVED'])), fields=('session',), name='one_unresolved_payment_per_visit')],
            },
        ),
    ]
