# Generated by Django 6.1 on 2026-09-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0018_paymentgateway_paymentattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='challenge_html',
            field=models.TextField(blank=True),
        ),
    ]
