# Generated by Django 6.1 on 2026-09-14 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0019_paymentattempt_card_brand_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentgateway',
            constraint=models.UniqueConstraint(condition=models.Q(('enabled', True)), fields=('restaurant_slug', 'venue_slug'), name='one_active_gateway_per_venue'),
        ),
    ]
