# Generated by Django 6.1 on 2026-09-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0020_paymentgateway_one_active_gateway_per_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requires_payment',
            field=models.BooleanField(default=False),
        ),
    ]
