# Generated by Django 6.1 on 2026-09-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0021_order_requires_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartline',
            name='allergens',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cartline',
            name='checkout_note',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='dineraccount',
            name='allergens',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
