# Generated by Django 6.1 on 2026-09-19 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0022_account_allergens_order_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='reservation_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='reservation_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='diner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='experience_app.diner'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='experience_app.order'),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='experience_app.tablesession'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CREATING', 'UNKNOWN', 'PENDING', 'APPROVED']), models.Q(('reservation_token', ''), _negated=True)), fields=('reservation_token',), name='one_unresolved_payment_per_reservation'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('diner__isnull', False), ('order__isnull', False), ('reservation_token', ''), ('session__isnull', False)), models.Q(('diner__isnull', True), ('order__isnull', True), ('session__isnull', True), models.Q(('reservation_token', ''), _negated=True)), _connector='OR'), name='payment_is_for_a_visit_or_a_reservation'),
        ),
    ]
