# Generated by Django 6.1 on 2026-09-24 00:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience_app', '0023_reservation_deposit_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='McpKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_slug', models.SlugField(max_length=60)),
                ('venue_slug', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('prefix', models.CharField(max_length=16)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['restaurant_slug', 'venue_slug'], name='experience__restaur_c88e3f_idx')],
            },
        ),
        migrations.CreateModel(
            name='McpPendingChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=20)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='experience_app.mcpkey')),
            ],
        ),
    ]
