import { expect, test } from '@playwright/test'

const base = '/burger-house/poblado'

test('Smart Menu: registro, nombre, favoritos persistentes, carrito, pedido e historial', async ({ page }) => {
  test.setTimeout(360_000)
  const email = `smart-menu-e2e-${Date.now()}@example.invalid`
  const errors: string[] = []
  page.on('pageerror', (e) => errors.push(e.message))
  await page.goto(base)
  await expect(page.getByRole('heading', { name: 'Encontremos el plato perfecto para ti' })).toBeVisible()
  await page.getByRole('button', {name:'Abrir navegación'}).click()
  await page.getByRole('link', {name:'Mi cuenta', exact:true}).click()
  await page.getByRole('button', { name: 'Crear mi cuenta' }).click()
  await page.getByLabel('Tu nombre', { exact: true }).fill('Camila Smart Test')
  await page.getByLabel('Correo electrónico', { exact: true }).fill(email)
  await page.getByLabel('Contraseña',{exact:true}).fill('Una clave inicial Smart42')
  await page.getByRole('checkbox', { name: /Acepto el uso/ }).check()
  await page.screenshot({ path: '/tmp/fig-review/registration-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Continuar', exact: true }).click()
  await page.getByLabel('Código de verificación', { exact: true }).fill('123456')
  await page.getByRole('button', { name: 'Verificar y entrar' }).click()
  await page.getByRole('button',{name:'Ver mi perfil',exact:true}).click()
  await expect(page.getByRole('heading', { name: 'Camila Smart Test', exact: true })).toBeVisible()
  await page.getByRole('link',{name:/^Contraseña/}).click()
  await page.getByLabel('Contraseña actual',{exact:true}).fill('Una clave inicial Smart42')
  await page.getByLabel('Nueva contraseña',{exact:true}).fill('Una clave de prueba Smart42')
  await page.getByLabel('Confirmar contraseña',{exact:true}).fill('Una clave de prueba Smart42')
  await page.getByRole('button',{name:'Guardar contraseña',exact:true}).click()
  await page.getByRole('button',{name:'Volver a mi perfil',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Camila Smart Test',exact:true})).toBeVisible()
  await page.getByRole('link', {name:/Información de mi cuenta/}).click()
  await page.getByLabel('Celular',{exact:true}).fill('+57 300 1234567')
  await page.getByRole('button',{name:'Guardar cambios',exact:true}).click()
  await expect(page.getByRole('status')).toHaveText('Cambios guardados')
  await page.reload()
  await expect(page.getByLabel('Celular',{exact:true})).toHaveValue('+57 300 1234567')
  await page.getByRole('link', {name:'Volver',exact:true}).click()
  await expect(page.getByRole('heading', {name:'Camila Smart Test',exact:true})).toBeVisible()
  await page.getByRole('link', {name:'Volver',exact:true}).click()
  await page.getByRole('button', {name:'Abrir navegación'}).click()
  await expect(page.getByText('Camila Smart Test',{exact:true})).toBeVisible()
  await page.getByRole('button', {name:'Cerrar navegación'}).click()
  await page.getByRole('button', { name: 'Guardar en favoritos: Hamburguesa Clásica', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Quitar de favoritos: Hamburguesa Clásica' })).toHaveAttribute('aria-pressed', 'true')
  await page.reload()
  await page.getByRole('button', {name:'Abrir navegación'}).click()
  await expect(page.getByText('Camila Smart Test',{exact:true})).toBeVisible()
  await page.getByRole('button', {name:'Cerrar navegación'}).click()
  await page.getByRole('button', {name:'Abrir navegación'}).click()
  await page.getByRole('link', {name:'Favoritos',exact:true}).click()
  await expect(page.getByRole('heading', { name: 'Tus favoritos', exact: true })).toBeVisible()
  await expect(page.locator('.sm-food-card').getByRole('heading', { name: 'Hamburguesa Clásica', exact: true })).toBeVisible()
  await expect(page.locator('.sm-food-card')).toHaveCount(1)
  await page.locator('.sm-food-link').click()
  await page.getByLabel('Más unidades').click()
  await page.getByLabel('¿Alguna indicación para cocina?').fill(`Prueba Smart Menu ${email}`)
  await page.screenshot({ path: '/tmp/fig-review/dish-mobile.png', fullPage: true })
  await page.getByRole('button', { name: /Agregar a mi pedido/ }).click()
  await expect(page.getByText('Agregado a tu pedido', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Ver mi pedido', exact: true }).click()
  await expect(page.locator('.sm-cart-line')).toHaveCount(1)
  await expect(page.locator('.sm-cart-line output')).toHaveText('2')
  await page.screenshot({ path: '/tmp/fig-review/cart-mobile.png', fullPage: true })
  await page.getByRole('button', { name: 'Confirmar pedido', exact: true }).click()
  await page.getByRole('button',{name:'Enviar a cocina',exact:true}).click()
  await expect(page.getByRole('heading', { name: 'Recibimos tu pedido' })).toBeVisible()
  await page.screenshot({ path: '/tmp/fig-review/status-mobile.png', fullPage: true })
  await page.getByRole('link', {name:'Volver',exact:true}).click()
  await expect(page.locator('.sm-history-card')).toHaveCount(1)
  await expect(page.locator('.sm-history-card')).toContainText('2 × Hamburguesa Clásica')
  await page.screenshot({ path: '/tmp/fig-review/history-mobile.png', fullPage: true })
  await page.getByRole('link',{name:'Valorar visita',exact:true}).click()
  await page.getByRole('button',{name:'Valorar mi experiencia'}).click()
  await page.getByRole('button',{name:'5: Excelente',exact:true}).click()
  await page.getByRole('button',{name:'Continuar',exact:true}).click()
  await page.getByRole('group',{name:'Valorar Hamburguesa Clásica'}).getByRole('button',{name:'5: Excelente'}).click()
  await page.getByRole('button',{name:'Enviar mi opinión'}).click()
  await expect(page.getByRole('status')).toHaveText('Tu opinión quedó guardada para este pedido.')
  await page.getByRole('button',{name:'Ver mis pedidos',exact:true}).click()
  await page.getByRole('button', { name: 'Volver a pedir' }).click()
  await expect(page.locator('.sm-cart-line output')).toHaveText('2')
  await page.getByRole('button', { name: 'Eliminar Hamburguesa Clásica' }).click()
  await expect(page.getByRole('heading', { name: 'Tu pedido está por empezar' })).toBeVisible()
  await page.getByRole('link', {name:'Volver',exact:true}).click()
  await page.getByRole('button', {name:'Abrir navegación'}).click()
  await page.getByRole('link', {name:'Mi cuenta',exact:true}).click()
  await page.getByRole('button', { name: 'Cerrar sesión' }).click()
  await expect(page.getByText('Qué gusto verte, Camila', { exact: true })).toHaveCount(0)
  await page.getByRole('button',{name:'Abrir navegación'}).click()
  await page.getByRole('link',{name:'Mi cuenta',exact:true}).click()
  await page.getByRole('link',{name:'Ya tengo una cuenta',exact:true}).click()
  await page.getByLabel('Correo electrónico',{exact:true}).fill(email)
  await page.getByLabel('Contraseña',{exact:true}).fill('Una clave de prueba Smart42')
  await page.getByRole('button',{name:'Entrar',exact:true}).click()
  await expect(page.getByRole('heading',{name:'Camila Smart Test',exact:true})).toBeVisible()
  await page.getByRole('link',{name:/Mis pedidos/}).click()
  await expect(page.locator('.sm-history-card')).toHaveCount(1)
  await page.getByRole('link',{name:'Valorar visita',exact:true}).click()
  await page.getByRole('button',{name:'Valorar mi experiencia'}).click()
  await expect(page.getByRole('button',{name:'5: Excelente',exact:true})).toHaveAttribute('aria-pressed','true')
  expect(errors).toEqual([])
})

test('Smart Menu se adapta a móvil, tablet y escritorio; la vista previa no escribe pedidos', async ({ page }) => {
  test.setTimeout(120_000)
  const mutations: string[] = []
  page.on('request', (r) => { if (r.method() !== 'GET' && r.url().includes('/api/v1/')) mutations.push(r.url()) })
  const preview = Buffer.from(JSON.stringify({ plantilla: 'S1', paleta: { acento: '#145A52', tintaTerciaria: '#F3C673' }, tipografia: { display: 'DM Sans' } })).toString('base64url')
  await page.goto(`${base}/carta/?vista_previa=${preview}`)
  await expect(page.getByText('Vista previa · cambios sin guardar')).toBeVisible()
  for (const width of [390, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await expect(page.locator('.sm-food-card').first()).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
    await page.screenshot({ path: `/tmp/fig-review/menu-${width}.png` })
  }
  await page.locator('.sm-food-link').nth(1).click()
  await page.getByRole('button', { name: /Agregar a mi pedido/ }).click()
  await expect(page.locator('.sm-error')).toContainText('vista previa')
  expect(mutations).toEqual([])
})
