# Generated by Django 6.1 on 2026-09-05 00:30

import django.db.models.deletion
import registry_app.utils.tokens
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=120)),
                ('odoo_url', models.URLField()),
                ('odoo_db', models.CharField(max_length=63)),
                ('odoo_login', models.CharField(max_length=120)),
                ('odoo_secret', models.TextField(help_text='Contraseña del usuario de servicio, cifrada con Fernet.')),
                ('pos_config_id', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='registry_app.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='TableToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=registry_app.utils.tokens.generate_token, max_length=12)),
                ('odoo_table_id', models.PositiveIntegerField()),
                ('table_number', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='registry_app.venue')),
            ],
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('restaurant', 'slug'), name='uniq_venue_slug_per_restaurant'),
        ),
        migrations.AddConstraint(
            model_name='tabletoken',
            constraint=models.UniqueConstraint(fields=('venue', 'token'), name='uniq_token_per_venue'),
        ),
    ]
