# Generated by Django 6.1 on 2026-09-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='brand_color',
            field=models.CharField(default='#C1873A', help_text='Color de acción, #RRGGBB', max_length=7),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='brand_font',
            field=models.CharField(default='Instrument Serif', help_text='Una de las seis fuentes curadas', max_length=40),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='brand_radius',
            field=models.PositiveSmallIntegerField(default=14, help_text='4 recto · 14 suave · 24 muy redondeado'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='greeting',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='logo_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='waiter_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='welcome',
            field=models.CharField(blank=True, default='', max_length=140),
        ),
    ]
