# Generated by Django 6.1 on 2026-09-21 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry_app', '0002_restaurant_brand_color_restaurant_brand_font_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_slug', models.SlugField(max_length=80)),
                ('venue_slug', models.SlugField(max_length=80)),
                ('with_table', models.BooleanField(help_text='La petición traía un token de mesa válido.')),
                ('client', models.GenericIPAddressField(blank=True, help_text='Dirección de quien pidió la resolución.', null=True)),
                ('released_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credential_releases', to='registry_app.venue')),
            ],
            options={
                'ordering': ['-released_at'],
            },
        ),
    ]
