'use strict';
const data=window.EXPORTY_AUDIT;
const $=id=>document.getElementById(id);
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=s=>s.name.replace(/^[0-9\uFE0F]+[.\s-]+/u,'');
let filtered=data.screens,selected=29;
$('summary').innerHTML=[[99,'capturas revisadas'],[data.summary.partial,'equivalentes parciales'],[data.summary.missingEquivalent,'sin equivalente'],[0,'certificadas idénticas'],[432,'archivos verificados']].map(([n,t])=>`<div><strong>${n}</strong><span>${t}</span></div>`).join('');
function assetCard(a){return `<article class="asset"><a href="source/${encodeURI(a.path)}" target="_blank" rel="noopener"><img loading="lazy" src="source/${encodeURI(a.path)}" alt="${escape(a.path.split('/').pop())}">${escape(a.path.split('/').pop())}</a><small>${escape(a.kind)} · ${a.installed?'Copia original desplegada':'Sin copia directa desplegada'}</small>${a.installed?`<small>${escape(a.installed)}</small>`:''}</article>`}
function show(){
 const s=data.screens.find(s=>s.number===selected),r=s.review;
 $('screen-select').value=String(selected);const pos=filtered.findIndex(s=>s.number===selected);$('previous').disabled=pos<=0;$('next').disabled=pos>=filtered.length-1;
 $('review').innerHTML=`<h2>${String(s.number).padStart(2,'0')} · ${escape(title(s))}</h2><span class="badge ${r.status==='sin-equivalente'?'missing':''}">${r.status==='parcial'?'Equivalente parcial · no idéntico':'Sin equivalente específico'}</span><p><strong>Observado en el original:</strong> ${escape(r.observed)}</p><p class="finding"><strong>Resultado:</strong> ${escape(r.difference)}</p><div class="comparison"><figure><figcaption>Original · <a href="source/${encodeURI(s.reference)}" target="_blank" rel="noopener">abrir completo</a></figcaption><div class="frame"><img src="source/${encodeURI(s.reference)}" alt="Original ${s.number}"></div></figure><figure><figcaption>Implementación actual${r.case?` · <a href="current/${r.case}.png" target="_blank" rel="noopener">abrir completa</a>`:''}</figcaption>${r.case?`<div class="frame"><img src="current/${r.case}.png" alt="Implementación ${escape(r.case)}"></div><p>Componentes reales; API interceptada para reproducir este estado sin escribir en el POS.</p>`:'<div class="frame empty"><strong>No existe una vista equivalente.</strong><p>La ausencia se comprobó en las rutas y componentes activos. No se presenta una captura del original como implementación.</p></div>'}</figure></div><details><summary>Assets referenciados en esta pantalla (${s.assets.filter(a=>a.kind!=='explicit').length})</summary><p>Referencias del mapa, incluidas las heredadas u ocultas.</p><div class="gallery">${s.assets.filter(a=>a.kind!=='explicit').map(assetCard).join('')}</div></details>`;
 history.replaceState(null,'',`#screen-${selected}`);
}
function filter(){const q=$('search').value.toLowerCase(),status=$('status').value;filtered=data.screens.filter(s=>(!status||s.review.status===status)&&`${s.number} ${s.name} ${s.review.observed} ${s.review.difference}`.toLowerCase().includes(q));$('screen-select').innerHTML=filtered.map(s=>`<option value="${s.number}">${s.number}. ${escape(title(s))}</option>`).join('');if(!filtered.length){$('review').innerHTML='<p>No hay pantallas con estos filtros.</p>';$('previous').disabled=$('next').disabled=true;return}if(!filtered.some(s=>s.number===selected))selected=filtered[0].number;show()}
$('search').addEventListener('input',filter);$('status').addEventListener('change',filter);$('screen-select').addEventListener('change',e=>{selected=Number(e.target.value);show()});for(const[id,delta]of[['previous',-1],['next',1]])$(id).onclick=()=>{selected=filtered[filtered.findIndex(s=>s.number===selected)+delta].number;show()};
function assets(){let q=$('asset-search').value.toLowerCase();$('asset-gallery').innerHTML=data.assets.filter(a=>a.kind!=='explicit'&&`${a.path} ${a.screens.join(' ')}`.toLowerCase().includes(q)).map(assetCard).join('')}
$('asset-search').addEventListener('input',assets);
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));for(const id of['screens','assets','method'])$(id).hidden=id!==button.dataset.tab;if(button.dataset.tab==='assets')assets()});
$('captures').innerHTML=data.evidence.map(e=>`<article class="asset"><a href="current/${e.name}.png" target="_blank" rel="noopener"><img loading="lazy" src="current/${e.name}.png" alt="${escape(e.name)}">${escape(e.name)}</a><small>/${escape(e.route)} · ${e.viewport.width} × ${e.viewport.height}</small><small>Errores JS: ${e.errors.length} · peticiones sin fixture: ${e.unhandled.length} · desbordamiento: ${e.overflow?'sí':'no'}</small><small>Fuentes disponibles: DM Sans ${e.fonts.display?'sí':'no'}, Mulish ${e.fonts.body?'sí':'no'}</small></article>`).join('');
const initial=Number(location.hash.replace('#screen-',''));if(data.screens.some(s=>s.number===initial))selected=initial;filter();
