import { test, expect } from '@playwright/test'
import { DEMO_ADMIN, startShiftAs } from './helpers/odoo'

test('recipe availability, batch editing and inventory history are accessible without changing live stock',async({page})=>{
 test.setTimeout(240000)
 await page.goto('/login')
 await page.getByLabel('Correo').fill('admin')
 await page.getByLabel('Contraseña').fill('admin')
 await page.getByRole('button',{name:/Entrar|Abrir mi turno/}).click()
 await startShiftAs(page,DEMO_ADMIN.name,DEMO_ADMIN.pin)
 await page.waitForURL(/\/(salon|caja)$/)
 await page.goto('/inventario')
 await page.getByRole('button',{name:/Hamburguesa Angus/}).click({timeout:60000})
 const recipe=page.getByRole('dialog',{name:'Receta · Hamburguesa Angus'})
 await expect(recipe.getByText('Costo de ingredientes por plato')).toBeVisible({timeout:30000})
 await expect(recipe.getByRole('columnheader',{name:'Pedidos pendientes'})).toBeVisible()
 await expect(recipe.getByRole('cell',{name:'Carne de res Angus',exact:true})).toBeVisible()
 await recipe.getByRole('button',{name:'Editar receta'}).click()
 await recipe.getByLabel('Porciones de la receta').fill('10')
 await recipe.getByLabel('Cantidad 1',{exact:true}).fill('2')
 await recipe.getByRole('button',{name:'Cancelar edición'}).click()
 await expect(recipe.getByText('Costo de ingredientes por plato')).toBeVisible()
 await page.screenshot({path:'/tmp/waiter-dev/restaurant-recipe.png'})
 await recipe.getByRole('button',{name:'Cerrar',exact:true}).click()
 await page.getByRole('tab',{name:'Ingredientes',exact:true}).click()
 await page.getByRole('button',{name:'Más opciones de Carne de res Angus',exact:true}).click()
 await page.getByRole('menuitem',{name:'Existencias y movimientos'}).click()
 const inventory=page.getByRole('dialog',{name:'Control de inventario · Carne de res Angus'})
 await expect(inventory.getByText('Últimos movimientos')).toBeVisible({timeout:30000})
 await inventory.getByLabel('Tipo de movimiento').selectOption('count')
 await expect(inventory.getByText(/Termina antes los pedidos/)).toBeVisible()
 await inventory.getByLabel('Cantidad del movimiento').fill('99')
 await inventory.getByLabel('Motivo o referencia').fill('Borrador de prueba, no aplicar')
 await page.screenshot({path:'/tmp/waiter-dev/restaurant-inventory.png'})
 await inventory.getByRole('button',{name:'Cerrar',exact:true}).click()
 await expect(inventory).toHaveCount(0)
})
