import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { FloorEditor } from '@/components/tables/FloorEditor'
import type { FloorDocument } from '@/lib/domain/floorPlan'
import { savePlan } from '@/lib/services/floorPlan'
import { checkPin } from '@/lib/services/employees'
import { useAuthStore } from '@/lib/stores/authStore'
jest.mock('@/lib/services/employees',()=>({checkPin:jest.fn()}))
jest.mock('@/lib/stores/authStore',()=>({useAuthStore:{getState:jest.fn()}}))
jest.mock('@/lib/services/floorPlan',()=>({savePlan:jest.fn()}))
const initial:FloorDocument={id:1,name:'Sala',revision:0,walls:[],zones:[],tables:[{id:1,key:'1',number:1,seats:6,zone:'',x:40,y:40,width:120,height:240},{id:2,key:'2',number:2,seats:4,zone:'',x:200,y:40,width:120,height:120}]}
beforeEach(()=>{
 Object.defineProperty(window,'PointerEvent',{value:MouseEvent,configurable:true})
 SVGElement.prototype.setPointerCapture=jest.fn()
 jest.clearAllMocks()
})
it('rotates into a collision, disables save and supports undo without writing',()=>{
 render(<FloorEditor initial={initial} configId={1} onCancel={jest.fn()} onSaved={jest.fn()}/> )
 const svg=screen.getByLabelText('Cuadrícula del restaurante')
 svg.getBoundingClientRect=()=>({left:0,top:0,right:1000,bottom:800,width:1000,height:800,x:0,y:0,toJSON:()=>null})
 fireEvent.pointerDown(screen.getByRole('button',{name:'Mesa 1, 6 personas'}),{clientX:100,clientY:100})
 fireEvent.pointerUp(svg,{clientX:100,clientY:100})
 fireEvent.click(screen.getByText('Rotar'))
 expect(screen.getByRole('button',{name:'Mesa 1, 6 personas, ubicación no válida'})).toBeInTheDocument()
 expect(screen.getByRole('button',{name:'Guardar'})).toBeDisabled()
 fireEvent.click(screen.getByRole('button',{name:'Deshacer'}))
 expect(screen.getByRole('button',{name:'Guardar'})).toBeEnabled()
 expect(savePlan).not.toHaveBeenCalled()
})
it('cancel leaves capacity edits unsaved',()=>{
 const cancel=jest.fn()
 render(<FloorEditor initial={initial} configId={1} onCancel={cancel} onSaved={jest.fn()}/> )
 fireEvent.pointerDown(screen.getByRole('button',{name:'Mesa 1, 6 personas'}),{clientX:100,clientY:100})
 fireEvent.pointerUp(screen.getByLabelText('Cuadrícula del restaurante'),{clientX:100,clientY:100})
 fireEvent.change(screen.getByLabelText('Capacidad (personas)'),{target:{value:'10'}})
 fireEvent.click(screen.getByRole('button',{name:'Cancelar'}))
 expect(cancel).toHaveBeenCalled()
 expect(initial.tables[0].seats).toBe(6)
 expect(savePlan).not.toHaveBeenCalled()
})

it('renews an expired PIN in place and saves the retained edits only after a valid PIN',async()=>{
 const saved=jest.fn(), startShift=jest.fn()
 ;(useAuthStore.getState as jest.Mock).mockReturnValue({employee:{id:7},startShift})
 ;(savePlan as jest.Mock).mockRejectedValueOnce(new Error('Valida el PIN de un administrador para modificar el plano o las zonas.')).mockResolvedValue(initial)
 ;(checkPin as jest.Mock).mockResolvedValueOnce({ok:false,reason:'wrong'}).mockResolvedValueOnce({ok:true,employee:{id:7,role:'admin'},attendanceId:3,token:'renewed'})
 render(<FloorEditor initial={initial} configId={1} onCancel={jest.fn()} onSaved={saved}/> )
 fireEvent.change(screen.getByLabelText('Nombre del piso'),{target:{value:'Sala editada'}})
 fireEvent.click(screen.getByRole('button',{name:'Guardar'}))
 const pin=await screen.findByLabelText('PIN del administrador')
 fireEvent.change(pin,{target:{value:'000000'}})
 fireEvent.click(screen.getByRole('button',{name:'Validar y guardar'}))
 await screen.findByText('El PIN no coincide. Revisa e intenta de nuevo.')
 expect(savePlan).toHaveBeenCalledTimes(1)
 expect(startShift).not.toHaveBeenCalled()
 fireEvent.change(pin,{target:{value:'123456'}})
 fireEvent.click(screen.getByRole('button',{name:'Validar y guardar'}))
 await waitFor(()=>expect(saved).toHaveBeenCalled())
 expect(startShift).toHaveBeenCalledWith({id:7,role:'admin'},3,'renewed')
 expect(savePlan).toHaveBeenLastCalledWith(1,expect.objectContaining({name:'Sala editada'}))
})
it('selects covered zones and the image from layers and moves only the chosen element',async()=>{
 const saved=jest.fn()
 ;(savePlan as jest.Mock).mockResolvedValue(initial)
 const plan={...initial,zones:[{id:'z',name:'Comedor',color:'#3b82f6',x:0,y:0,width:800,height:600}]}
 render(<FloorEditor initial={plan} background="/plano.png" configId={1} onCancel={jest.fn()} onSaved={saved}/> )
 const svg=screen.getByLabelText('Cuadrícula del restaurante')
 svg.getBoundingClientRect=()=>({left:0,top:0,right:1000,bottom:800,width:1000,height:800,x:0,y:0,toJSON:()=>null})
 fireEvent.click(screen.getByRole('button',{name:'Seleccionar capa: Zona Comedor'}))
 fireEvent.pointerDown(screen.getByRole('button',{name:'Mover elemento seleccionado'}),{clientX:90,clientY:90})
 fireEvent.pointerMove(svg,{clientX:170,clientY:90})
 fireEvent.pointerUp(svg,{clientX:170,clientY:90})
 fireEvent.click(screen.getByRole('button',{name:'Seleccionar capa: Imagen de referencia'}))
 fireEvent.pointerDown(screen.getByRole('button',{name:'Mover elemento seleccionado'}),{clientX:90,clientY:90})
 fireEvent.pointerMove(svg,{clientX:170,clientY:154})
 fireEvent.pointerUp(svg,{clientX:170,clientY:154})
 fireEvent.click(screen.getByRole('button',{name:'Guardar'}))
 await waitFor(()=>expect(saved).toHaveBeenCalled())
 const result=(savePlan as jest.Mock).mock.calls.at(-1)[1]
 expect(result.zones[0]).toMatchObject({x:100,y:0})
 expect(result.backgroundSize).toEqual({x:100,y:80,width:1200,height:800})
 expect(result.tables).toEqual(initial.tables)
})
it('drags past the old origin and saves the whole layout with relative positions intact',async()=>{
 const saved=jest.fn()
 ;(savePlan as jest.Mock).mockResolvedValue(initial)
 render(<FloorEditor initial={initial} configId={1} onCancel={jest.fn()} onSaved={saved}/> )
 const svg=screen.getByLabelText('Cuadrícula del restaurante')
 svg.getBoundingClientRect=()=>({left:0,top:0,right:1000,bottom:800,width:1000,height:800,x:0,y:0,toJSON:()=>null})
 fireEvent.pointerDown(screen.getByRole('button',{name:'Mesa 1, 6 personas'}),{clientX:100,clientY:100})
 fireEvent.pointerMove(svg,{clientX:20,clientY:20})
 fireEvent.pointerUp(svg,{clientX:20,clientY:20})
 expect(screen.getByRole('button',{name:'Guardar'})).toBeEnabled()
 expect(screen.getByRole('button',{name:'Mover elemento seleccionado'})).toHaveAttribute('x','-60')
 fireEvent.click(screen.getByRole('button',{name:'Ver todo'}))
 const transform=svg.querySelector('g[transform]')!.getAttribute('transform')!
 const translation=transform.match(/translate\(([^ ]+) ([^)]+)\)/)!
 expect(Number(translation[1])).toBeGreaterThan(30)
 expect(Number(translation[2])).toBeGreaterThan(30)
 fireEvent.click(screen.getByRole('button',{name:'Guardar'}))
 await waitFor(()=>expect(saved).toHaveBeenCalled())
 const result=(savePlan as jest.Mock).mock.calls.at(-1)[1]
 expect(result.tables[0]).toMatchObject({x:0,y:0})
 expect(result.tables[1]).toMatchObject({x:260,y:100})
})

// Falla si una mesa en rojo deja de decir por qué, o si el aviso de la cabecera deja de llevar hasta ella.
it('explains why a table is invalid and jumps to it from the header',()=>{
 render(<FloorEditor initial={initial} configId={1} onCancel={jest.fn()} onSaved={jest.fn()}/> )
 fireEvent.click(screen.getByRole('button',{name:'Seleccionar capa: Mesa 1'}))
 fireEvent.click(screen.getByText('Rotar'))
 expect(screen.getByRole('alert')).toHaveTextContent('Está encima o demasiado cerca de otra mesa.')
 fireEvent.keyDown(window,{key:'Escape'})
 expect(screen.queryByRole('region',{name:'Elemento seleccionado'})).not.toBeInTheDocument()
 fireEvent.click(screen.getByRole('button',{name:/2 mesas por corregir/}))
 expect(screen.getByRole('region',{name:'Elemento seleccionado'})).toBeInTheDocument()
})

// Falla si los atajos dejan de funcionar, si duplicar repite el número de mesa, o si una tecla pulsada mientras se
// escribe el nombre del piso borra o mueve lo seleccionado.
it('duplicates, nudges, deletes and switches tools from the keyboard, but never while typing',()=>{
 render(<FloorEditor initial={initial} configId={1} onCancel={jest.fn()} onSaved={jest.fn()}/> )
 fireEvent.click(screen.getByRole('button',{name:'Seleccionar capa: Mesa 2'}))
 fireEvent.keyDown(window,{key:'d',ctrlKey:true})
 expect(screen.getByRole('button',{name:'Seleccionar capa: Mesa 3'})).toHaveAttribute('aria-pressed','true')
 expect(screen.getByRole('button',{name:'Mesa 3, 4 personas'})).toBeInTheDocument()
 fireEvent.keyDown(window,{key:'ArrowDown'})
 expect(screen.getByRole('button',{name:'Mover elemento seleccionado'})).toHaveAttribute('y','60')
 fireEvent.keyDown(screen.getByLabelText('Nombre del piso'),{key:'Delete'})
 expect(screen.getByRole('button',{name:'Seleccionar capa: Mesa 3'})).toBeInTheDocument()
 fireEvent.keyDown(window,{key:'Delete'})
 expect(screen.queryByRole('button',{name:'Seleccionar capa: Mesa 3'})).not.toBeInTheDocument()
 fireEvent.keyDown(window,{key:'z',ctrlKey:true})
 expect(screen.getByRole('button',{name:'Seleccionar capa: Mesa 3'})).toBeInTheDocument()
 fireEvent.keyDown(window,{key:'p'})
 expect(screen.getByRole('button',{name:'Dibujar pared'})).toHaveAttribute('aria-pressed','true')
 fireEvent.keyDown(window,{key:'Escape'})
 expect(screen.getByRole('button',{name:'Seleccionar elementos'})).toHaveAttribute('aria-pressed','true')
})
